--- #YAML:1.0
name:               Apache-Session-Wrapper
version:            0.34
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Apache::Session:   1.81
    Class::Container:  0
    Exception::Class:  0
    File::Spec:        0
    File::Temp:        0
    Module::Build:     0
    Params::Validate:  0.7
    Scalar::Util:      0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
